### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by barracuda156** [rahra/utdns#1]
@rahra Which license does it have?

**Comment by rahra** [comment]
I didn't think about it much since it's just a tiny tool.
Any preference? Usually I attach GPL.

**Comment by barracuda156** [comment]
I was not planning to use this commercially, so GPL will do.

**Comment by barracuda156** [comment]
P. S. For the context: I am looking for a solution to have DNS over TCP on a powerpc version of 10.6.8, since for a reason yet unknown UDP is just broken, so we have no internet :) Preferably something light, so one is not required to build something like bind9, which pulls in a dependency on a modern gcc etc.

**Comment by rahra** [comment]
It will do it.
I know from several people who use it for similar corner cases, even in bigger networks.

**Comment by rahra** [comment]
I published a new release with GPL and added a document from one of my blogs which doesn't exist anymore.
Don't hestitate to contact me.
