### ISSUE TITLE
Autotools do not generate configure correctly on macOS

### ISSUE THREAD

**Issue by barracuda156** [rahra/utdns#2]
@rahra Could you please take a look? Not really sure why, but autoconf generates configure script with an error:
```
--->  Extracting utdns-1.2.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_utdns/utdns/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/utdns/utdns-1.2.tar.gz' | /usr/bin/gnutar --no-same-owner -xf - 
--->  Configuring utdns
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_utdns/utdns/work/utdns-1.2" && autoreconf --install --verbose 
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /opt/local/bin/aclocal 
/opt/local/share/aclocal/zthread.m4:34: warning: underquoted definition of AM_PATH_ZTHREAD
/opt/local/share/aclocal/zthread.m4:34:   run info Automake 'Extending aclocal'
/opt/local/share/aclocal/zthread.m4:34:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
fatal: not a git repository (or any of the parent directories): .git
autoreconf: configure.ac: tracing
fatal: not a git repository (or any of the parent directories): .git
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /opt/local/bin/autoconf
fatal: not a git repository (or any of the parent directories): .git
autoreconf: running: /opt/local/bin/autoheader
autoreconf: running: /opt/local/bin/automake --add-missing --copy --no-force
configure.ac:6: installing './compile'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory '.'
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_utdns/utdns/work/utdns-1.2" && ./configure --prefix=/opt/local 
./configure: line 4: .: filename argument required
.: usage: . filename [arguments]
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_utdns/utdns/work/utdns-1.2" && ./configure --prefix=/opt/local 
Exit code: 2
```
This is what fails:
```
#! /bin/sh
# Guess values for system-dependent variables and create Makefiles.
# Generated by GNU Autoconf 2.72 for utdns 1.1.r-n 0
.
#
# Report bugs to <bf@abenteuerland.at>.
#
#
# Copyright (C) 1992-1996, 1998-2017, 2020-2023 Free Software Foundation,
# Inc.
#
#
# This configure script is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.
## -------------------- ##
## M4sh Initialization. ##
## -------------------- ##
```
I.e. the dot on line 4 should not be there.

**Comment by barracuda156** [comment]
This works fine though:
```
AC_INIT([utdns], [1.2], [bf@abenteuerland.at])
```

**Comment by rahra** [comment]
Ok, I know where this comes from. I'll fix it.
Nevertheless, could you try to download the tar.gz (https://github.com/rahra/utdns/releases/download/v1.2/utdns-1.2.r1265.tar.gz) from the releases and try if this compiles fine.
Just unpack, then `./configure`, then `make`.

**Comment by barracuda156** [comment]
@rahra Thank you, it is indeed better to avoid requiring autotools. I am in fact already running it – compiled 10 min ago – and it works! Amazingly simple, no-dependency solution.

(I am still to see whether everything can work this way, but browsing works, and I can fetch tarballs, so MacPorts is functional normally. The OS is finally usable.)

Your app is awesome!

**Comment by rahra** [comment]
Everything will work. This is absolutely network transparent. It's only slightly slower (milliseconds) because of TCP has to do a 3-way handshake for each request.

**Comment by barracuda156** [comment]
@rahra BTW, is there a way to connect when I do not know what is supposed to be DNS server locally? Currently I have two OS on this machine, an older version with normally working UDP (and therefore DHCP and DNS) and a newer one but with a broken UDP. So on the system in question DHCP does not work. However, I can check what macOS assigns in Network Preferences on a system with working UDP – and use DNS server IP from there with `utdns` (at least that is what worked for me). However without a second system I would not know what IP to use.

**Comment by rahra** [comment]
Well, not directly. That's exactly what DHCP is made for.
But you have other options. You could run utdns on a dedicated machine and let all others connect to this one. So configure the DNS to be the IP of the machine which runs utdns. It's a network service so it may not necessarily run locally.
The second thing you could do is to use a public DNS of which you know the IP in advance, e.g. 8.8.8.8, 8.8.4.4, 1.1.1.1, and so on (see https://public-dns.info/ and https://www.lifewire.com/free-and-public-dns-servers-2626062). This will always work as long as there is no firewall restricting access.

**Comment by rahra** [comment]
I just removed the dependency in configure.ac.
It should now also work if you check it out directly from Github and then run `./bootstrap` and then `./configure` and `make`.

**Comment by barracuda156** [comment]
Thank you! BTW, I added `utdns` to MacPorts: https://ports.macports.org/port/utdns

**Comment by rahra** [comment]
Thank you very much!
So I close this as resolved.
